import os
from anthropic import Anthropic
from dotenv import load_dotenv

load_dotenv()

client = Anthropic(api_key=os.getenv('ANTHROPIC_API_KEY'))

def run_chat():
    print('You: (type exit to quit)')
    system_message = "Your name is A. You are a helpful tutor and friendly assistant who helps students learn about technology and computer science. You explain things clearly and always encourage curiosity and motivate learning."
    history = []

    while True:
        user_input = input('>> ')

        if user_input.lower() == 'exit':
            break

        history.append({'role': 'user', 'content': user_input})
        print('History:', history)
        #the massages will be 6 ,3 for the user and 3 for the assistant
        # the API  needs to know the history each time cause it doesn't remember the previous messages so you need to send the history each time you send a new message
        response = client.messages.create(
            model='claude-haiku-4-5-20251001',
            max_tokens=300,
            # when i changed the max tokens to 50 the massge was cut off and it was not able to answer the question fully so i think it is the limit of the tokens that can be used in a single message
            temperature=0.7,
            #when I changed the temperature to 0 the response was completly identical , while at 1 it was more different wording structure... 
            #I think it is for controling the creativity of the response
            system=system_message,
            messages=history
        )

        reply = response.content[0].text
        
        # usage.input_tokens: The total count of tokens sent to Claude
        #usage.output_tokens: The count of tokens generated by Claude in its response message.
        #bonus 1
        print(f'Input Tokens: {response.usage.input_tokens}' , f'Output Tokens: {response.usage.output_tokens}')
        print(f'Claude: {reply}')
        

        history.append({'role': 'assistant', 'content': reply})

run_chat()

#Lab 2 reflection:
#PA : maybe like Utiilty Meters like electricity and water that the more you use, the more you pay.
# if I delete..: 1) history.append({'role': 'user', 'content': user_input}) : the Ai won't remember any of the previous conversations if you don't store the history of the conversation and for the input_tokens it will be less because the input will be less.
#2)history.append({'role': 'assistant', 'content': reply}): the Ai won't remember any of the previous conversations if you don't store the history and for the output_tokens it will be less because the output will be less. 
#3)print('History so far:', history) : yes the AI will not remember any of the previous conversations
# I didn't have any bug this lab .




#Lab 1 reflection:
#chat gpt you talk to the website UI but here you talk directly to the backend .
#Reflection: 
#1.when you go to new place like a country or a new workplace you need to give them your CV or applying for a visa or a passport
#2.1) history.append({'role': 'assistant', 'content': reply}) : the Ai won't remember any of the previous conversations if you don't store the history of the conversation.
#2)load_dotenv(): i think it would start but won't reach the API key cuz its in .env and it needs to be loaded 
#3) temperature=0.7: i think its for controling the speed of response and it won't be a visible change
#3. first I thougth it was the API key fault but then i realized that it was the terminal it needed a virtual enviromment in a certain way  i think there is a vere huge gape between them 